# Generated by Django 2.1.15 on 2020-05-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_postmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
